import SidePanel from '@/components/SidePanel';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Wellcom! My Blog! <Yuu.log />',
  description: 'Generated by create yuu',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <main className="w-full h-full flex">
          <SidePanel />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
